// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchly_2._0.WebApi.Context;

#nullable disable

namespace Switchly_2._0.WebApi.Context.Migrations
{
    [DbContext(typeof(SwitchlyDbContext))]
    [Migration("20260518153718_AddRolloutSchedules")]
    partial class AddRolloutSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ConversionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserKey", "OccurredAt");

                    b.HasIndex("ProjectEnvironmentId", "EventName", "OccurredAt");

                    b.ToTable("ConversionEvents");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enable new dashboard",
                            IsArchived = false,
                            Key = "new_dashboard",
                            Name = "New Dashboard",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Type = "Boolean"
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultRolloutKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DefaultRolloutPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEnvironmentId");

                    b.HasIndex("FeatureFlagId", "ProjectEnvironmentId")
                        .IsUnique();

                    b.ToTable("FeatureFlagEnvironments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            DefaultRolloutKind = "AllUsers",
                            DefaultRolloutPercentage = 100,
                            FeatureFlagId = new Guid("00000000-0000-0000-0000-000000000040"),
                            IsEnabled = true,
                            ProjectEnvironmentId = new Guid("00000000-0000-0000-0000-000000000030"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            DefaultRolloutKind = "Off",
                            DefaultRolloutPercentage = 0,
                            FeatureFlagId = new Guid("00000000-0000-0000-0000-000000000040"),
                            IsEnabled = false,
                            ProjectEnvironmentId = new Guid("00000000-0000-0000-0000-000000000031"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            DefaultRolloutKind = "Off",
                            DefaultRolloutPercentage = 0,
                            FeatureFlagId = new Guid("00000000-0000-0000-0000-000000000040"),
                            IsEnabled = false,
                            ProjectEnvironmentId = new Guid("00000000-0000-0000-0000-000000000032"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironmentVariantWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureFlagEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariantId");

                    b.HasIndex("FeatureFlagEnvironmentId", "VariantId")
                        .IsUnique();

                    b.ToTable("FeatureFlagEnvironmentVariantWeights");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureFlagEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RolloutKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RolloutPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("SegmentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SegmentGroupId");

                    b.HasIndex("FeatureFlagEnvironmentId", "SegmentGroupId")
                        .IsUnique();

                    b.ToTable("FeatureFlagSegmentTargetings");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargetingVariantWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureFlagSegmentTargetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariantId");

                    b.HasIndex("FeatureFlagSegmentTargetingId", "VariantId")
                        .IsUnique();

                    b.ToTable("FeatureFlagSegmentTargetingVariantWeights");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FlagExposureEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOn")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectEnvironmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VariantId");

                    b.HasIndex("FeatureFlagId", "OccurredAt");

                    b.HasIndex("UserKey", "FeatureFlagId");

                    b.ToTable("FlagExposureEvents");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Demo Organization",
                            PublicKey = "demo-org-public",
                            Slug = "demo-org"
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Role = "Owner",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "",
                            IsArchived = false,
                            Key = "demo-project",
                            Name = "Demo Project",
                            OrganizationId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("ProjectEnvironments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = true,
                            Key = "dev",
                            Name = "Development",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000020"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = false,
                            Key = "stg",
                            Name = "Staging",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000020"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = false,
                            Key = "prod",
                            Name = "Production",
                            ProjectId = new Guid("00000000-0000-0000-0000-000000000020"),
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("ProjectSettings");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectSettingValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEnvironmentId");

                    b.HasIndex("ProjectSettingId", "ProjectEnvironmentId")
                        .IsUnique();

                    b.ToTable("ProjectSettingValues");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.RolloutSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("FeatureFlagEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreScheduleSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TargetVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagEnvironmentId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Active', 'Paused', 'Draft')");

                    b.HasIndex("TargetVariantId");

                    b.ToTable("RolloutSchedules");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.RolloutScheduleStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RolloutScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolloutScheduleId", "StepIndex")
                        .IsUnique();

                    b.ToTable("RolloutScheduleSteps");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LogicalOperator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("SegmentGroups");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogicalOperator")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Operator")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ParentRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SegmentGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TraitKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRuleId");

                    b.HasIndex("SegmentGroupId");

                    b.ToTable("SegmentRules");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "demo@switchly.dev",
                            Name = "Demo User",
                            PasswordHash = "DEMO_HASH"
                        });
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId", "Key")
                        .IsUnique();

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ConversionEvent", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.ProjectEnvironment", "ProjectEnvironment")
                        .WithMany()
                        .HasForeignKey("ProjectEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("ProjectEnvironment");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlag", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Project", "Project")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("Environments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.ProjectEnvironment", "ProjectEnvironment")
                        .WithMany("FeatureFlagEnvironments")
                        .HasForeignKey("ProjectEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");

                    b.Navigation("ProjectEnvironment");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironmentVariantWeight", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany("VariantWeights")
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Variant", "Variant")
                        .WithMany("EnvironmentWeights")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagEnvironment");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargeting", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany("SegmentTargetings")
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.SegmentGroup", "SegmentGroup")
                        .WithMany("FeatureFlagTargetings")
                        .HasForeignKey("SegmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagEnvironment");

                    b.Navigation("SegmentGroup");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargetingVariantWeight", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargeting", "FeatureFlagSegmentTargeting")
                        .WithMany("VariantWeights")
                        .HasForeignKey("FeatureFlagSegmentTargetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Variant", "Variant")
                        .WithMany("TargetingWeights")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagSegmentTargeting");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FlagExposureEvent", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany()
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.ProjectEnvironment", "ProjectEnvironment")
                        .WithMany()
                        .HasForeignKey("ProjectEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeatureFlag");

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("ProjectEnvironment");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.OrganizationMember", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.User", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Project", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectSetting", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Project", "Project")
                        .WithMany("Settings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectSettingValue", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.ProjectEnvironment", "ProjectEnvironment")
                        .WithMany("SettingValues")
                        .HasForeignKey("ProjectEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.ProjectSetting", "ProjectSetting")
                        .WithMany("Values")
                        .HasForeignKey("ProjectSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectEnvironment");

                    b.Navigation("ProjectSetting");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.RolloutSchedule", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany()
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly_2._0.WebApi.Entities.Variant", "TargetVariant")
                        .WithMany()
                        .HasForeignKey("TargetVariantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeatureFlagEnvironment");

                    b.Navigation("TargetVariant");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.RolloutScheduleStep", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.RolloutSchedule", "RolloutSchedule")
                        .WithMany("Steps")
                        .HasForeignKey("RolloutScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutSchedule");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentGroup", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.Organization", "Organization")
                        .WithMany("SegmentGroups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentRule", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.SegmentRule", "ParentRule")
                        .WithMany("Children")
                        .HasForeignKey("ParentRuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Switchly_2._0.WebApi.Entities.SegmentGroup", "SegmentGroup")
                        .WithMany("Rules")
                        .HasForeignKey("SegmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentRule");

                    b.Navigation("SegmentGroup");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Variant", b =>
                {
                    b.HasOne("Switchly_2._0.WebApi.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("Variants")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlag", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.Navigation("SegmentTargetings");

                    b.Navigation("VariantWeights");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.FeatureFlagSegmentTargeting", b =>
                {
                    b.Navigation("VariantWeights");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");

                    b.Navigation("SegmentGroups");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.Navigation("FeatureFlagEnvironments");

                    b.Navigation("SettingValues");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.ProjectSetting", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.RolloutSchedule", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentGroup", b =>
                {
                    b.Navigation("FeatureFlagTargetings");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.SegmentRule", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.User", b =>
                {
                    b.Navigation("OrganizationMembers");
                });

            modelBuilder.Entity("Switchly_2._0.WebApi.Entities.Variant", b =>
                {
                    b.Navigation("EnvironmentWeights");

                    b.Navigation("TargetingWeights");
                });
#pragma warning restore 612, 618
        }
    }
}
